name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-15]
        addrsize: ["64"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: AlchemyViewer/action-autobuild@v5
        with:
          addrsize: ${{ matrix.addrsize }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: alchemyviewer/action-autobuild-release@v4
        with:
          public: true
